controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

position_controller:
  ros__parameters:
    joints:
      - fl_hip_to_body
      - fl_femur_to_hip
      - fl_tibia_to_femur
      - fr_hip_to_body
      - fr_femur_to_hip
      - fr_tibia_to_femur
      - bl_hip_to_body
      - bl_femur_to_hip
      - bl_tibia_to_femur
      - br_hip_to_body
      - br_femur_to_hip
      - br_tibia_to_femur

# joint_state_broadcaster:
#   ros__parameters:
